config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'messages#index'
  root 'groups#index'
  resources :users, only:[:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
  # resources :images, only: [:index, :create]
  # root "images#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :messages
  has_many :users, through: :group_users
  validates :name, presence: true, uniqueness: true

  def show_last_message
    if (last_message = messages.last).present?
      last_message.content? ? last_message.content : '画像が投稿されています'
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :file_name, ImageUploader
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :content, presence: true, unless: :image?
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages
  has_many :group_users
  has_many :groups, through: :group_users
  mount_uploader :image, ImageUploader        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image]) #image追加を許可
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]
  
  def index
  end
  
  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを編集しました'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, { :user_ids => [] })
  end

  def set_group
    @group = Group.find(params[:id])
  end
  
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  skip_before_action :verify_authenticity_token
  def index
  end

  def create
    @image = Image.new(file_name: params[:file])
    if @image.save
      render json: { message: "success", fileID: @image.id }, :status => 200
    else
      render json: { error: @image.errors.full_messages.join(',')}, :status => 400
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path(@group)  }
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
    @user = User.find(params[:id]) #画像アップ用
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :image) #image追加
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/avatars/index.html.erb
<h1>My Images</h1>
<%= form_for(Image.new, html: {multipart: true, class: "dropzone"}) do |f|  %>
  <div class="fallback">
    <%= f.file_field :file_name, multiple: true %>
  </div>
<% end %>

<script type="text/javascript">
  $(function() {
    // disable auto discover
    Dropzone.autoDiscover = false;
    $(".dropzone").dropzone({
      maxFilesize: 1,
      addRemoveLinks: true
    });
  });
</script>

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right
      / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
      = f.collection_check_boxes :user_ids, User.all, :id, :name
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
      - @group.users.each do |user|
        .main-header__left-box__member-list
          = image_tag user.image.url, class: 'message__user-image'
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.wrapper

  = render 'devise/shared/side-var-super'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render 'form', { group: @group }

app/views/images/index.html.erb
<h1>My Images</h1>
<%= form_for(Image.new, html: {multipart: true, class: "dropzone"}) do |f|  %>
  <div class="fallback">
    <%= f.file_field :file_name, multiple: true %>
  </div>
<% end %>

<script type="text/javascript">
  $(function() {
    // disable auto discover
    Dropzone.autoDiscover = false;
    $(".dropzone").dropzone({
      maxFilesize: 1,
      addRemoveLinks: true
    });
  });
</script>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MyAppChat
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = yield

app/views/messages/_message.html.haml
.message-box
  .message-box__left
    .message-box__left__user-image
      = image_tag message.user.image.url, class: 'message__user-image'
    .message-box__left__user-name
      = message.user.name
  .message-box__right
    .message-box__right__message
      - if message.content.present?
        .message__content
          = message.content
      = image_tag message.image.url, class: 'lower-message__image' if message.image.present?
    .message-box__right__date
      = message.created_at.strftime("%H:%M")

app/views/messages/index.html.haml
.wrapper
  = render 'devise/shared/side-var-super'
  .chat-main
    .main-header
      .main-header__left-box
        .main-header__left-box__current-group
          = @group.name
        .main-header__left-box__menber-box
          - @group.users.each do |user|
            .main-header__left-box__member-list
              = image_tag user.image.url, class: 'message__user-image'
      .main-header__right-box
        .main-header__right-box__edit-btn
          = link_to 'Edit', edit_group_path(@group)
    .messages
      = render @messages
    .form
      = form_for [@group, @message] do |f|
        .form__mask
          = f.label :image, class: 'form__mask__image' do
            %i.fa.fa-image.fa-1.5x.fa-fw
            = f.file_field :image, class: 'hidden'
        = f.text_field :content, class: 'form__message', placeholder: 'メッセージを入力'
        .form__mask
          = f.label :image, class: 'form__mask__image' do
            %i.fa.fa-smile-o.fa-1.5x
            = f.file_field :image, class: 'hidden'
        = f.submit 'Send', class: 'form__submit'

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .field
          = image_tag @user.image.url
          = f.file_field :image
        .actions
          = f.submit "Update", class: 'btn'